jumpstart = [
    {"Set": "JMP", "Theme" : "BASRI", "Rarity": "M", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "UNICORNS", "Rarity": "M", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "TEFERI", "Rarity": "M", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "MILLING", "Rarity": "M", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "LILIANA", "Rarity": "M", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "PHYREXIAN", "Rarity": "M", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "CHANDRA", "Rarity": "M", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "SEISMIC", "Rarity": "M", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "GARRUK", "Rarity": "M", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "WALLS", "Rarity": "M", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "RAINBOW", "Rarity": "M", "PrimaryColor": "M"},
    {"Set": "JMP", "Theme" : "ANGELS", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "DOGS", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "ENCHANTED", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "PIRATES", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "SPIRITS", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "UNDER THE SEA", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "DISCARDING", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "ROGUES", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "WITCHCRAFT", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "DRAGONS", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "LIGHTNING", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "MINOTAURS", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "CATS", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "ELVES", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "LANDS", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "DOCTOR", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "FEATHERED FRIENDS", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "HEAVILY ARMORED", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "LEGION", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "JMP", "Theme" : "ABOVE THE CLOUDS", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "ARCHAEOLOGY", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "WELL-READ", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "WIZARDS", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "JMP", "Theme" : "MINIONS", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "REANIMATED", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "SPOOKY", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "VAMPIRES", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "JMP", "Theme" : "DEVILISH", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "GOBLINS", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "SMASHING", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "SPELLCASTING", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "JMP", "Theme" : "DINOSAURS", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "PLUS ONE", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "PREDATORY", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "JMP", "Theme" : "TREE-HUGGING", "Rarity": "C", "PrimaryColor": "G"},

    {"Set": "J22", "Theme" : "KNIGHTS", "Rarity": "M", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "VEHICLES", "Rarity": "M", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "SHAPESHIFTERS", "Rarity": "M", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "SNOW", "Rarity": "M", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "RATS", "Rarity": "M", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "UNLUCKY THIRTEEN", "Rarity": "M", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "SPEEDY", "Rarity": "M", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "SPICY", "Rarity": "M", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "ELDRAZI", "Rarity": "M", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "PRIMATES", "Rarity": "M", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "URZA'S", "Rarity": "M", "PrimaryColor": "M"},
    {"Set": "J22", "Theme" : "CONSTELLATION", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "SPIRITS", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "TEAMWORK", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "FAERIES", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "GO TO SCHOOL", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "SCRYING", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "BONEYARD", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "DEMONS", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "MORBID", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "CYCLING", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "DRAGONS", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "EXPERIMENTAL", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "GIGANTIC", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "LANDFALL", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "MULTI-HEADED", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "BLINK", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "CATS", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "HOLY", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "LAW", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J22", "Theme" : "DETECTIVE", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "INVENTIVE", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "MERFOLK", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "THINK AGAIN", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J22", "Theme" : "CRUEL", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "FANGS", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "GROSS", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "ZOMBIES", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J22", "Theme" : "FIERY", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "GOBLINS", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "RAID", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "TREASURE", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J22", "Theme" : "ELVES", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "FEROCIOUS", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "INSECTS", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "J22", "Theme" : "WOLVES", "Rarity": "C", "PrimaryColor": "G"},

    {"Set": "DMU", "Theme" : "COALITION CORPS", "Rarity": "U", "PrimaryColor": "W"},
    {"Set": "DMU", "Theme" : "COALITION LEGION", "Rarity": "U", "PrimaryColor": "W"},
    {"Set": "DMU", "Theme" : "ARCANE MISCHIEF", "Rarity": "U", "PrimaryColor": "U"},
    {"Set": "DMU", "Theme" : "MYSTIC MISCHIEF", "Rarity": "U", "PrimaryColor": "U"},
    {"Set": "DMU", "Theme" : "TOTALLY MERCILESS", "Rarity": "U", "PrimaryColor": "B"},
    {"Set": "DMU", "Theme" : "TOTALLY RUTHLESS", "Rarity": "U", "PrimaryColor": "B"},
    {"Set": "DMU", "Theme" : "READY TO ATTACK", "Rarity": "U", "PrimaryColor": "R"},
    {"Set": "DMU", "Theme" : "READY TO CHARGE", "Rarity": "U", "PrimaryColor": "R"},
    {"Set": "DMU", "Theme" : "BEAST TERRITORY", "Rarity": "U", "PrimaryColor": "G"},
    {"Set": "DMU", "Theme" : "MONSTER TERRITORY", "Rarity": "U", "PrimaryColor": "G"},
    
    {"Set": "BRO", "Theme" : "INFANTRY", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "BRO", "Theme" : "POWERSTONES", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "BRO", "Theme" : "UNEARTH", "Rarity": "S", "PrimaryColor": "B"},  ##causes scryfall error?
    {"Set": "BRO", "Theme" : "WELDED", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "BRO", "Theme" : "TITANIC", "Rarity": "S", "PrimaryColor": "G"},
    
    {"Set": "ONE", "Theme" : "MITE-Y", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "ONE", "Theme" : "PROGRESS", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "ONE", "Theme" : "CORRUPTION", "Rarity": "S", "PrimaryColor": "B"},
    {"Set": "ONE", "Theme" : "REBELLIOUS", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "ONE", "Theme" : "TOXIC", "Rarity": "S", "PrimaryColor": "G"},
    
    {"Set": "MOM", "Theme" : "BROOD", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "MOM", "Theme" : "OVERACHIEVER", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "MOM", "Theme" : "EXPENDABLE", "Rarity": "S", "PrimaryColor": "B"},
    {"Set": "MOM", "Theme" : "REINFORCEMENT", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "MOM", "Theme" : "BUFF", "Rarity": "S", "PrimaryColor": "G"},
    
    {"Set": "LTR", "Theme" : "COURAGEOUS", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "LTR", "Theme" : "TRICKSY", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "LTR", "Theme" : "MORDOR", "Rarity": "S", "PrimaryColor": "B"},
    {"Set": "LTR", "Theme" : "MARAUDERS", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "LTR", "Theme" : "JOURNEY", "Rarity": "S", "PrimaryColor": "G"},
    {"Set": "LTR", "Theme" : "MORTALS", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "LTR", "Theme" : "CUNNING", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "LTR", "Theme" : "ORCISH", "Rarity": "S", "PrimaryColor": "B"},
    {"Set": "LTR", "Theme" : "RIDERS", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "LTR", "Theme" : "ELVEN", "Rarity": "S", "PrimaryColor": "G"},

    #With CLU Azorius 1 is W and Azorius 2 is U - this is true for the other guild packs:  https://mtg.fandom.com/wiki/Ravnica:_Clue_Edition/Decklists
    {"Set": "CLU", "Theme" : "AZORIUS SENATE", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "CLU", "Theme" : "ORZHOV SYNDICATE", "Rarity": "S", "PrimaryColor": "W"},
    {"Set": "CLU", "Theme" : "HOUSE DIMIR", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "CLU", "Theme" : "IZZET LEAGUE", "Rarity": "S", "PrimaryColor": "U"},
    {"Set": "CLU", "Theme" : "CULT OF RAKDOS", "Rarity": "S", "PrimaryColor": "B"},
    {"Set": "CLU", "Theme" : "GOLGARI SWARM", "Rarity": "S", "PrimaryColor": "B"},
    {"Set": "CLU", "Theme" : "GRUUL CLANS", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "CLU", "Theme" : "BOROS LEGION", "Rarity": "S", "PrimaryColor": "R"},
    {"Set": "CLU", "Theme" : "SELESNYA CONCLAVE", "Rarity": "S", "PrimaryColor": "G"},
    {"Set": "CLU", "Theme" : "SIMIC COMBINE", "Rarity": "S", "PrimaryColor": "G"},

    {"Set": "J25", "Theme" : "PRIDEFUL", "Rarity": "M", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "GIDDYAP", "Rarity": "M", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "ILLUSIONS", "Rarity": "M", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "NINJAS", "Rarity": "M", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "SNAKES", "Rarity": "M", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "NEFARIOUS", "Rarity": "M", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "TOO MANY", "Rarity": "M", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "BURNING", "Rarity": "M", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "DINNER", "Rarity": "M", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "MODIFIED", "Rarity": "M", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "CHAOS", "Rarity": "M", "PrimaryColor": "M"},
    {"Set": "J25", "Theme" : "ANGELS", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "HEROES", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "LEGION", "Rarity": "R", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "OF THE COAST", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "DROWNED", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "WIZARDS", "Rarity": "R", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "TREASURES", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "N'ER-DO-WELLS", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "ICKY", "Rarity": "R", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "DRAGONS", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "COPIED", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "WARRIORS", "Rarity": "R", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "FUN GUYS", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "BEASTS", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "DINOSAURS", "Rarity": "R", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "HEALERS", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "STALWART", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "ARMED", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "ENCHANTED", "Rarity": "C", "PrimaryColor": "W"},
    {"Set": "J25", "Theme" : "SOARING", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "SURPRISE!", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "BOOKWORMS", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "INVENTIVE", "Rarity": "C", "PrimaryColor": "U"},
    {"Set": "J25", "Theme" : "CLERICS", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "VAMPIRES", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "GRAVE ROBBERS", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "GHASTLY", "Rarity": "C", "PrimaryColor": "B"},
    {"Set": "J25", "Theme" : "STOKED", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "GOBLINS", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "BLOODY", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "ZEALOTS", "Rarity": "C", "PrimaryColor": "R"},
    {"Set": "J25", "Theme" : "ENCOUNTER", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "EXPLORERS", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "ELVES", "Rarity": "C", "PrimaryColor": "G"},
    {"Set": "J25", "Theme" : "LANDFALL", "Rarity": "C", "PrimaryColor": "G"},

    {"Set": "FDN", "Theme" : "CATS", "Rarity": "U", "PrimaryColor": "W"},
    {"Set": "FDN", "Theme" : "HEALING", "Rarity": "U", "PrimaryColor": "W"},
    {"Set": "FDN", "Theme" : "WIZARDS", "Rarity": "U", "PrimaryColor": "U"},
    {"Set": "FDN", "Theme" : "PIRATES", "Rarity": "U", "PrimaryColor": "U"},
    {"Set": "FDN", "Theme" : "VAMPIRES", "Rarity": "U", "PrimaryColor": "B"},
    {"Set": "FDN", "Theme" : "UNDEAD", "Rarity": "U", "PrimaryColor": "B"},
    {"Set": "FDN", "Theme" : "GOBLINS", "Rarity": "U", "PrimaryColor": "R"},
    {"Set": "FDN", "Theme" : "INFERNO", "Rarity": "U", "PrimaryColor": "R"},
    {"Set": "FDN", "Theme" : "ELVES", "Rarity": "U", "PrimaryColor": "G"},
    {"Set": "FDN", "Theme" : "PRIMAL", "Rarity": "U", "PrimaryColor": "G"},
]
#To fix for display --- string.lower().title() should capitalize the first letter of each string, including after dashes

sets = {"JMP": {"Name": "JumpStart 2020", "SetCode": "JMP", "ScryfallFrontSetCode": "fjmp", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/e/e4/Jumpstart_expansion_symbol.png/revision/latest?cb=20191012054123"}, 
        "J22": {"Name": "JumpStart 2022", "SetCode": "J22", "ScryfallFrontSetCode": "fj22", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/7/7c/J22_expansion_symbol.png/revision/latest?cb=20221021110742"},
        "J25": {"Name": "JumpStart 2025", "SetCode": "J25", "ScryfallFrontSetCode": "fj25", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/5/53/J25_expansion_symbol.png/revision/latest?cb=20240802205728"},
        "FDN": {"Name": "JumpStart 2025 Beginner Box", "SetCode": "FDN", "ScryfallFrontSetCode": "ffdn", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/d/d9/FDN_expansion_symbol.png/revision/latest?cb=20240802203917"},
        "DMU": {"Name": "Dominaria United JumpStart", "SetCode": "DMU", "ScryfallFrontSetCode": "fdmu", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/6/65/DMU_expansion_symbol.png/revision/latest?cb=20221208023938"},
        "BRO": {"Name": "The Brother's War JumpStart", "SetCode": "BRO", "ScryfallFrontSetCode": "fbro", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/1/12/BRO_expansion_symbol.png/revision/latest?cb=20221208023049"},
        "ONE": {"Name": "Phyrexia: All Will Be One JumpStart", "SetCode": "ONE", "ScryfallFrontSetCode": "fone", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/7/70/ONE_expansion_symbol.png/revision/latest?cb=20221208023207"},
        "MOM": {"Name": "March of the Machine JumpStart", "SetCode": "MOM", "ScryfallFrontSetCode": "fmom", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/5/50/MOM_expansion_symbol.png/revision/latest?cb=20221213222255"},
        "LTR": {"Name": "The Lord of the Rings: Tales of Middle-earth JumpStart", "SetCode": "LTR", "ScryfallFrontSetCode": "fltr", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/7/7b/LTR_expansion_symbol.png/revision/latest?cb=20230221204226"},
        "CLU": {"Name": "Ravnica: Clue Edition", "SetCode": "CLU", "ScryfallFrontSetCode": "fclu", "SetIconImageUrl": "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/f/ff/CLU_expansion_symbol.png/revision/latest?cb=20231205221115"}
}
